export const FETCH_SAVES = 'FETCH_SAVES';
export const FETCH_SAVES_REJECTED = 'FETCH_SAVES_REJECTED';
export const FETCH_SAVES_FULFILLED = 'FETCH_SAVES_FULFILLED';
export const ADD_SAVE = 'ADD_SAVE';
export const DELETE_SAVE = 'DELETE_SAVE';

export const LOAD_TOP_STORIES_SUCCESS = 'LOAD_TOP_STORIES_SUCCESS';
